language: java
sudo: false
stages:
  - compile
  - test
  - deploy
env:
  - FOO=one
  - FOO=two
jobs:
  include:
    - stage: compile
      script: mvn clean install
    - stage: deploy
script: mvn clean install